spring:
  application:
    name: file-storage-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:file_storage}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG